cc_test(
    name = "hello_test",
    size = "small",
    srcs = ["hello_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test1",
    size = "small",
    srcs = ["test1_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test2",
    size = "small",
    srcs = ["test2_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test3",
    size = "small",
    srcs = ["test3_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test4",
    size = "small",
    srcs = ["test4_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test5",
    size = "small",
    srcs = ["test5_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test6",
    size = "small",
    srcs = ["test6_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test7",
    size = "small",
    srcs = ["test7_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test8",
    size = "small",
    srcs = ["test8_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test9",
    size = "small",
    srcs = ["test9_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test10",
    size = "small",
    srcs = ["test10_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "test10",
    size = "small",
    srcs = ["test11_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)
